### ISSUE TITLE
Website: Add note, tags and organization info to webhook

### ISSUE THREAD

**Issue by robinsmidsrod** [newreleasesio/cli-go#13]
This is a feature request for the website, not the CLI (not sure how to report issues on the website).

Would it be possible to include organization info (id+name, at least), tag information and note (the yellow field) when sending a webhook? 

This would be quite useful to use a single webhook receiver for multiple organizations, and using tags to classify how the webhook handles the received information. I tend to use the note for information on which server(s) have the software installed and installation method that is used for the particular software.

**Comment by janos** [comment]
That should be doable. It would be nice addition to the webhook, indeed.

The best place to submit such comments is https://newreleases.io/contact.

**Comment by janos** [comment]
Additional fields (account, tags and project note) to the webhook request body and json template has been added. More details on https://newreleases.io/webhooks.
