### ISSUE TITLE
better changelog

### ISSUE THREAD

**Issue by rafipiccolo** [newreleasesio/cli-go#14]
i dont know if its the right place for this, i didn't find any other issue board for the project.

i would like better detection of the changes detected by newreleases.
I believe that newreleases only watches the release tab of github. which is already nice.

But for some of the projects i watch, they dont fill properly the releases tab, it's empty :
https://gitlab.com/html-validate/html-validate/-/releases

Some others only fill the tags tab. (i dont have an example right know, but i've seen 2 of them recently)

And others only fill this file
https://gitlab.com/html-validate/html-validate/-/blob/master/CHANGELOG.md
which is usually generated by the same tool.

is it possible ?

**Comment by janos** [comment]
Hi, I am sorry for responding after so long time. NewReleases cannot reliable parse changelog files, but for qute some time it provides release notes from GitLab releases just as it does from the GitHub, and even from other GitLab instances such as Debian, Freedesktop, GNOME, KDE and Xfce.
