### ISSUE TITLE
Homebrew installation option

### ISSUE THREAD

**Issue by yermulnik** [newreleasesio/cli-go#15]
It would be great to have an option to install the tool using Homebrew. Either via Core (canonical) repository or via 3rd-party Tap.
Thanks in advance.

**Comment by janos** [comment]
Hi, thank you for a suggestion. We will see what can be done.

**Comment by yermulnik** [comment]
Closing as resolved. Thanks a bunch!

**Comment by yermulnik** [comment]
btw non-cask Brew installations works on Linux as well in most cases (where source provides linux binaries) and I'm the one that uses this approach. thanks again.

**Comment by janos** [comment]
Wonderful. I will update the readme. Thank you for suggesting this improvement!

**Comment by yermulnik** [comment]
Thank you for implementing this 🤝 JFYI: I can confirm Brew installation works w/o issues on Linux.
