### ISSUE TITLE
Self-hosted instanse 

### ISSUE THREAD

**Issue by itsecforu** [newreleasesio/cli-go#16]
Hi everyone and thanks for the great tool. Can you please tell me if there is any option to deploy the instance on your private cloud on prem? maybe docker compose or helm chart?

**Comment by janos** [comment]
Hello and thanks! There is no on prem option available for NewReleases. We have focused our efforts on the online service, only. Which does not mean that sometime in the future there will be other possibilities.

**Comment by matbgn** [comment]
Hi,

Any plan to reconsider the open-sourcing of the server part? Or at least having a packaged binary for on-prem?

Best,
Mat

**Comment by janos** [comment]
Hi, unfortunately, we are unable to support such on-prem product currently. Mainly due to architectural changes and to provide adequate support.
