### ISSUE TITLE
Unable to subscribe to repo containing dots

### ISSUE THREAD

**Issue by pschmitt** [newreleasesio/cli-go#2]
**Describe the bug**
The CLI is returning an error when trying to subscribe to repository that contains `.` chars.

**To Reproduce**
```
$ newreleases project add github pschmitt/test.test
Error: GitHub project not found.
$ newreleases project add github resume/resume.github.com
Error: GitHub project not found.
```

**Expected behavior**
Subscribe to the repo.

**Additional context**
These repos actually exist:
- https://github.com/pschmitt/test.test
- https://github.com/resume/resume.github.com

**Comment by janos** [comment]
Hi, Philipp. Thanks for a detailed issue report.

We have fixed the issue that you described for https://github.com/resume/resume.github.com and similar repositories.

But, https://github.com/pschmitt/test.test repository is empty and it is still considered as not found.

**Comment by pschmitt** [comment]
Yeah I just created it to test the here described issue. Thanks for the quick update ;)
