### ISSUE TITLE
Enhancement: Add provision to add projects from any self-hosted GitLab

### ISSUE THREAD

**Issue by ranjithrajv** [newreleasesio/cli-go#4]
I would like to thank you creating an amazing project and adding a great feature enhancement to add projects from GitLab instances of Debian, FreeDesktop, GNOME & KDE.

Looking at the high pace of projects moving to self-hosted GitLab instances, I'd request to add a provision to add projects from any self-hosted GitLab instance.

**Comment by janos** [comment]
Hi, Ranjith. This enhancement is in the roadmap for sure. It is completely correct that self-hosted GitLab instances are on the rise. There is a need to switch from currently fixed list of providers to the one that a user can add and configure. It contains some dose of complexity which require some time. I cannot say when this feature will be implemented, but it is identified as an important one.

**Comment by janos** [comment]
Closing the issue as NewReleases tracks GitLab instances for more than two years, already.
