### ISSUE TITLE
Enhancement: Add option to display direct project links on Slack

### ISSUE THREAD

**Issue by pyxelr** [newreleasesio/cli-go#5]
Hi,
Currently, the newreleases Slack app automatically generates a message with a link to the newreleases page, which also requires the visitor to log in (e.g., `apache/airflow on GitHub`: `newreleases.io/github/apache/airflow?org=<id>`).

This approach makes it pretty hard to quickly view the release notes, so I would like to suggest an option to display direct project links instead, e.g., to the main GitHub page, like [https://github.com/apache/airflow](https://github.com/apache/airflow). Ideally, it could link to the specific release notes page, such as [https://github.com/apache/airflow/releases/tag/2.1.3](https://github.com/apache/airflow/releases/tag/2.1.3).

Thanks!

**Comment by janos** [comment]
Hi, Paweł.

Thanks for suggestion.

The link to the upstream page with release notes is in the header of the page (for non logged in users), for example https://newreleases.io/github/apache/airflow?version=helm-chart%2F1.1.0. Link to the project itself is in the header also.

We are providing links only to NewReleases pages in notifications as we cannot ensure that the links on external sites will exist in the future. We are also providing release notes where they exist and also the link to the upstream page. It does require two clicks as a consequence.

Cheers!

**Comment by pyxelr** [comment]
Hi Jason,

Thank you for the response, and I understand your point of view. The current header is not very explicit, but I understand it is your design choice.

In any case, today I found an issue with the URLs on Slack. When I am already logged in on `newreleases.io` to organization A (or simply to my personal account), and I am trying to open a Slack URL with a different organization in its `?` parameter, e.g. [https://newreleases.io/github/matplotlib/matplotlib?org=263533fd1647](https://newreleases.io/github/matplotlib/matplotlib?org=263533fd1647), then I am receiving a `404` error, as on the attached screenshot.

The current solution is to either open such a link without being logged in, or to remove the URL part after `?`.

Cheers!


![2021-08-24_13-35-36](https://user-images.githubusercontent.com/30161753/130609684-692a5ba4-3c62-4d6f-b069-e0966fabccd3.png)

**Comment by janos** [comment]
Hi @pyxelr. Yes, this behaviour is currently expected, as you are logged in with a different organization than the one for which the notification is received. We will improve the user experience to allow to explicitly switch to a different organization instead to present the 404 page.

I am closing this issue, as it is not related to the cli-go project, but to the website.
