### ISSUE TITLE
Add complete custom webhooks

### ISSUE THREAD

**Issue by pblgomez** [newreleasesio/cli-go#6]
I was thinking in integrating this sending a custom webhook to create a Jira ticket, but the options are limited right now or I don't seem to find a way to do it as it requires multinested json parameters. Is it possible?

**Comment by janos** [comment]
You are right. Webhook custom request is limited to object with only top level string fields. As one possible solution, a JSON templating could be added to cover requirements for more complex webhook request bodies.

**Comment by janos** [comment]
Basic support for webhook request bodies with completely custom JSON templates is released. The option is available under the webhook settings. UX is quite simple right now, but it will improve over time.

Thanks @pblgomez for the suggestion.

**Comment by pblgomez** [comment]
wow, great, I'll try to test it today, That is awesome, thank you.

> Basic support for webhook request bodies with completely custom JSON templates is released. The option is available under the webhook settings. UX is quite simple right now, but it will improve over time.
> 
> Thanks @pblgomez for the suggestion.

**Comment by pblgomez** [comment]
Hey, Maybe a button to trigger a test showing the output to check everything it's working would be good ! :)

**Comment by janos** [comment]
Yes, that is needed, indeed. There were already similar requests and we have that in plan.

**Comment by pblgomez** [comment]
Weird thing happens as tests are good but when a new release comes 3 jira tickets are created not 1.

**Comment by janos** [comment]
Since I need information about your account on NewReleases, would you mind sending a contact message https://newreleases.io/contact with your email and the project name that is in question?
