### ISSUE TITLE
Document tag search and creation API

### ISSUE THREAD

**Issue by robinsmidsrod** [newreleasesio/cli-go#9]
I noticed that the web UI supports adding tags (and notes), but these features are not documented in the API.

Any chance of getting these into the documentation?

My use-case is that I'd want to import e.g. a PHP composer file and tag all the imported dependencies with the URL/repo of the PHP composer file. Then I'd want to find all the releases for all projects that has this tag in the given timeframe. The plan is to use this to create Jira issues to inform developers that there are new releases to their dependencies.

**Comment by janos** [comment]
Tag management is not available trough the API, currently. We will plan to add methods to list tags and associate projects with tags by extending API and to document new methods.

The use-case is very realistic. Thank you for reporting it.

**Comment by janos** [comment]
A complete tags support is released with https://github.com/newreleasesio/cli-go/releases/tag/v0.1.9. That includes complete tags management and projects list filtering.
